// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CrawlWebsite(arg1, arg2, arg3) {
  return window['go']['main']['App']['CrawlWebsite'](arg1, arg2, arg3);
}

export function ExportCSV(arg1) {
  return window['go']['main']['App']['ExportCSV'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function StopCrawl() {
  return window['go']['main']['App']['StopCrawl']();
}
