// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CrawlWebsite(arg1:string,arg2:number):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function StopCrawl():Promise<void>;
